---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:js
        - yarn test

    - stage: "Floating dependencies"
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-release
    - env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-beta
    - env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-canary
    - env: TEST_SUITE=frontend EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: TEST_SUITE=backend # node tests (node_tests dir)

before_install:
  - npm config set spin false
  - npm install -g npm@4
  - npm --version

script:
  - if [ "$TEST_SUITE" = "backend" ]; then npm run test:node; fi
  - if [ "$TEST_SUITE" = "frontend" ]; then node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO; fi
